### ISSUE TITLE
Please provide build directions/script

### ISSUE THREAD

**Issue by cdosoftei** [MarcusTomlinson/DSPatcher#1]
Hi @MarcusTomlinson!

Thank you for putting together this project as well as the https://github.com/MarcusTomlinson/DSPatch core library.

I am having a hard time building DSPatcher on Debian 9; could you provide building directions, or better yet, an install script such as the one for [DSPatch](https://github.com/MarcusTomlinson/DSPatch/blob/master/install.sh)?

**Comment by MarcusTomlinson** [comment]
Hey, yeah this project does need some love (It’s still very much in Alpha). I’ll try to address this soon.
